image:
  repository: registry.ivanchenko.io/library/stremio-addons
  pullPolicy: IfNotPresent
  tag: main
  proxyTag: main-proxy

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

eneyidaProxySecret: ~

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 7777
  proxyPort: 8888

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
  hosts:
    - host: stremio.ivanchenko.io
      paths:
        - path: /
          pathType: Prefix
          svcPort: 7777
    - host: rezka-proxy.ivanchenko.io
      paths:
        - path: /
          pathType: Prefix
          svcPort: 8888
  tls:
    - secretName: stremio-tls
      hosts:
        - stremio.ivanchenko.io
        - rezka-proxy.ivanchenko.io

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
