apiVersion: v1
kind: Service
metadata:
  name: {{ include "stremio-addons.fullname" . }}-proxy
  labels:
    {{- include "stremio-addons.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    app.kubernetes.io/name: {{ include "stremio-addons.name" . }}-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
